version: "3.8"

services:
  test-db:
    image: postgres:15
    container_name: expense-ease-test-db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    networks:
      - test-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  test-net:
